### ISSUE TITLE
make_npdata issue(s)

### ISSUE THREAD

**Issue by diingus** [friendlyanon/CFW2OFW-Helper#10]
The latest release (v11) will hang on `Running make_npdata ...` after the window loses focus.

It stops doing anything after finishing with `make_npdata`, but is still responsive (`ctrl+c` breaks it)

![image](https://user-images.githubusercontent.com/10434228/37099541-d68386ac-2220-11e8-9bb2-cb6f6727ed50.png)
![image](https://user-images.githubusercontent.com/10434228/37099582-f78c6c60-2220-11e8-8f1b-7a0260b049ae.png) 
(`make_npdata.exe` is never listed as a process)

EDIT: It seems to start again randomly on focus loss.

**Comment by friendlyanon** [comment]
I'm not experiencing anything of sorts. Must be a Windows 10 quirk. The executable is probably getting blocked by another process, either Defender, some anti malware thing or your AV.

**Comment by chadbell30** [comment]
Windows 7 64bit getting a unexpected error xxxx07 can’t run  npdata click ok to exit the first error was a dll was missing any idea why

**Comment by chadbell30** [comment]
Think iv found the fix by using npdata and the 2 .dll with cfw2ofw v1.2 gui

**Comment by friendlyanon** [comment]
Can one of you please download this executable instead and try running the task which it spits out upon failure in a new command line? I don't know what causes make_npdata to fail, since I didn't write that program, but this should help you by maybe getting a meaningful error message. If you don't get anything, it could be that you are using a terribly bad AV that straight up blocks UPX compressed executables.
[test.zip](https://github.com/friendlyanon/CFW2OFW-Helper/files/1853830/test.zip)

**Comment by chadbell30** [comment]
Il try it now for you bud

**Comment by chadbell30** [comment]
Well not sure if you changed anything or just added output log but I’m not getting any dll or 0xc0007d error now

**Comment by chadbell30** [comment]
It’s worked buddy

**Comment by Lethiur1** [comment]
I'm experiencing the same problem as the OP, it will ahng on "Running make_npdata.exe", my AV is disabled and tried your hotfix but it didn't work unfortunately.

**Comment by profesaurus** [comment]
I'm having the same problem.  Freezes at "Running make_npdata".  AV is disabled.

Edit: Actually it just seems like some games take a lot longer to process than others. The first few I did, make_npdata took less than a second to complete, but others take multiple minutes.

**Comment by jeanDenison** [comment]
Am experiencing the same problem, am running a clean window 7 OS without any antivirus with firewall turn off on a VM . getting npdata did not start correctly.

**Comment by friendlyanon** [comment]
Unfortunate, but make_npdata isn't really my program, so I can't tell what's the issue with it. I'm not going to completely integrate its funcionality into this helper either, because this program is pretty much on maintenance mode now.
