### ISSUE TITLE
Npdata not working 

### ISSUE THREAD

**Issue by chadbell30** [friendlyanon/CFW2OFW-Helper#13]
Hi I’m running Windows 7 64bi npdata error about a missing .dll so I add the dll and now I get 0x00007d error click ok to exit

**Comment by friendlyanon** [comment]
Use #10 for any further make_npdata issues.

**Comment by chadbell30** [comment]
You’re cfw2ofw gui 1.2 npdata and 2 .dlls seems to have fixed v11 for me it’s Successfully mAde pkgs now signing them with Han tools il keep you updated if you like

**Comment by friendlyanon** [comment]
I do not support the broken GUI program and you don't need anything from it to convert games using my tool.
