### ISSUE TITLE
Destiny patch 

### ISSUE THREAD

**Issue by chadbell30** [friendlyanon/CFW2OFW-Helper#14]
Hi buddy the npdata issue seems to be fixed but I’m having a problem with 
with destiny 1.13 patch it sits at 23% has been for 2 days so I downloaded it manually put it in patch folder but it saying failed any ideas thanks

**Comment by friendlyanon** [comment]
If you have issues with downloading that means you have connection problems.
The names of the patch files must match exactly. You can copy the name of the patch file from the terminal window of this tool and rename the patches manually. For example Minecraft requires these files to be present:
* `EP4433-BLES01976_00-MINECRAFTPS30363-A0164-V0100-PE.pkg`
* `EP4433-BLES01976_00-MINECRAFTPS30363-A0166-V0100-PE.pkg`
* `EP4433-BLES01976_00-MINECRAFTPS30363-A0167-V0100-PE.pkg`
