### ISSUE TITLE
BLES00134

### ISSUE THREAD

**Issue by amritpalh** [friendlyanon/CFW2OFW-Helper#15]
Hi Mate,

Fantastic work! I keep getting this error when I drag my folder over cfw2ofw helper I don't know why.

![cfw2ofw helper error](https://user-images.githubusercontent.com/37944282/38164872-fb07b7d8-3502-11e8-97e8-1df685f3b0fa.png)

Please take a look at the screenshot.

Kind Regards.

**Comment by friendlyanon** [comment]
Only accepts `PS3_GAME` folders.
