### ISSUE TITLE
Older PARAM.SFO reading problems

### ISSUE THREAD

**Issue by magicbob93** [friendlyanon/CFW2OFW-Helper#16]
I was trying to convert Folklore (BCES00050) using your script, but it stops with the message"Title, category and App_ver missing".

I opened my param.sfo on notepad and app_ver isn't there, but version is. 
I changed version to app_ver on my param.sfo and it worked.
So I think you should check for both app_ver and version strings.

Sorry if I sounded rude, English is not my first language

Best regards

**Comment by romuerto** [comment]
Hi im the same problem here with folklore but what do u do? u edited param.sfo just with netepad or with param editor
si hablas español mejor

**Comment by magicbob93** [comment]
I edited param.sfo on notepad ++
Just changed "VERSION" to "APP_VER" 

Just had the same problem with heavenly sword and fixed it by doing the same thing.

**Comment by romuerto** [comment]
Hi im the same problem here with folklore but what do u do? u edited param.sfo just with netepad or with param editor
si hablas español mejor

**Comment by romuerto** [comment]
many thanks it works!!! i almost get crazy looking for a solution... due to the compatibilty list says Folklore have no installation  issues
 i will do the same for heavnly sword and vikings, it may happen with older titles

**Comment by romuerto** [comment]
have you already installed the Folklore dlcs? just install normal or edit the param.sfo

**Comment by magicbob93** [comment]
I just installed the dlcs and they are working ok, no problem. Just reassigned the pkg and it was ready to go.
The only thing that I noted is that the version number doesn't appear on PlayStation "information" menu about the game (When you highlight the game and press triangle).
But nonetheless, the game works just fine.

You can try changing back the param.sfo to the original after the conversion is finished.
I didn't test it but it should work okay, since the "Version" attribute just shows info about update, and doesn't direct involve ID or title.
As long as you remember which pkg is installed for that game, you're good to go!

**Comment by romuerto** [comment]
Well i think that the version number is a little issue, what really matters is that the game and dlcs works properly, anyway i will try to changing back to the original param file in Heavenly sword.

i really appreciate your help, have a nice day :)

**Comment by friendlyanon** [comment]
Should be fixed now with v13, hopefully.
