### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by Archor-btw** [friendlyanon/CFW2OFW-Helper#18]
I have made a backup for Gran Turismo 6 (BCES01893). I have download all updates but the program indicates an error on 1.08 and 1.10. I have suppr and re-download all majs but the same error... Can you help me please ?

**Comment by chadbell30** [comment]
Same here with destiny on the 1.13 update all I got told was make sure the name is correct and it was bit still had the error but my report got closed without a fix 😐
