### ISSUE TITLE
*** is not compatible, but this could be untrue, because there was an error detected while parsing the update entry

### ISSUE THREAD

**Issue by ilwsm** [friendlyanon/CFW2OFW-Helper#19]
What do next?
What mean "could be untrue"?

**Comment by animekai** [comment]
means the game u try to convert doesnt have updates, without updates from psn servers, the game can not be converted to pkg to play it on ofw. which game are you trying to convert?

**Comment by flowcr** [comment]
The same thing happens to me, I do not know what to do with this
 http://prntscr.com/jib47w

**Comment by animekai** [comment]
flowcr, as the note said, the game has freezes and black screens, is unplayable, so the program skips the convertion of this especific game, although the game is in somehow convertible, but it won't be playable, thats why the program skip it.
