### ISSUE TITLE
Erreur to read the EBOOT.BIN file

### ISSUE THREAD

**Issue by chronoss09** [friendlyanon/CFW2OFW-Helper#2]
I want to convert my NBA 2K17 BLES02242 (EUR) but it give me an error to move the eboot.bin

<a href="http://www.casimages.com/img.php?i=1705170157206637115046035.png" target="_blank" title="hebergement d'image"><img src="http://nsm07.casimages.com/img/2017/05/17//1705170157206637115046035.png" border="0" alt="hebergement d'image" /></a>

And please, make the log to not delete the source folder, make it to just duplicate the source and not delete...

**Comment by friendlyanon** [comment]
The conversion is technically finished after make_npdata is done without errors.

Settings is on the to-do list.
