### ISSUE TITLE
Insert Game Cd

### ISSUE THREAD

**Issue by ayasns** [friendlyanon/CFW2OFW-Helper#20]
converting taken tag 2 and when run it in ofw 4.82 error message insert game cd

**Comment by Archor-btw** [comment]
I had the same problem 2 months ago, the only way to fix it ... It is to delete the game ! (even when converting it, there will always be this error :\) Sorry :s

**Comment by friendlyanon** [comment]
Not really an issue of this program. You may try tweaking the relevant settings in the ini file and ask for troubleshooting on reddit or a forum.
