### ISSUE TITLE
Warnings if a game is impossible to convert because of the unexistence update file

### ISSUE THREAD

**Issue by animekai** [friendlyanon/CFW2OFW-Helper#21]
This is an idea more than a issue, i wanted to convert spiderman 3, but i didn't realize later that this game doesn't have an update, soo is impossible to convert it in ofw, so that's why i want to say, a method to recognize games who are impossible to convert, pops a message saying, "this game can not be converted to ofw because there is not updates for this game", or something like that warning users the impossibility to converted some games.

i know i can check the compactibility list on internet, but a little message could save me hours of researching why spiderman 3 can not be converted.

thanks for your hard work, greatings and bye.

**Comment by friendlyanon** [comment]
https://www.reddit.com/r/ps3homebrew/wiki/cfw2ofw#wiki_checking_compatibility

**Comment by Ahmed-Soudi** [comment]
Can't be converted because the update have psn eboot kind and the method depend on it. (You can't run bluray eboot from hdd, only psn eboot)
