### ISSUE TITLE
 Patching PARAM.SFO ... failed

### ISSUE THREAD

**Issue by marciogalvao89** [friendlyanon/CFW2OFW-Helper#23]
--- CFW2OFW Helper v11h1 ---
// https://github.com/friendlyanon/CFW2OFW-Helper/
Game identified: BCES01893
Target ID: NPEA01893

21 patches were found for Gran Turismo6
Size of updates: 11 222 479 504 bytes
Depending on your internet speed and the size of updates this might take some
time, so please be patient!
Downloading or checking SHA1 hash:
EP9001-BCES01893_00-0000000000000000-A0102-V0101-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0103-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0104-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0105-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0106-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0107-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0108-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0109-V0100-PE.pkg ... done99%
EP9001-BCES01893_00-0000000000000000-A0110-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0111-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0112-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0113-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0114-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0115-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0116-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0117-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0118-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0119-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0120-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0121-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0122-V0100-PE.pkg ... done

Extracting PKGs:
EP9001-BCES01893_00-0000000000000000-A0102-V0101-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0103-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0104-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0105-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0106-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0107-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0108-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0109-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0110-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0111-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0112-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0113-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0114-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0115-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0116-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0117-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0118-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0119-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0120-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0121-V0100-PE.pkg ... done
EP9001-BCES01893_00-0000000000000000-A0122-V0100-PE.pkg ... done

Processing game files:
  Creating directory structure ... done
  Moving content ... done
  Patching PARAM.SFO ... failed
Error:
Acesso negado ao caminho 'D:\CFW2OFW Converter V11\Gran_Turismo6_(BCES01893)\NPEA01893\PARAM.SFO'.
Press any key to exit . . .

**Comment by friendlyanon** [comment]
Not really an issue with this program, something is preventing it from accessing the sfo.

**Comment by viktormelnychuk** [comment]
Uncheck the "Read only" for PARAM.SFO in the PS_GAME folder
