### ISSUE TITLE
make_npdata error

### ISSUE THREAD

**Issue by oresths-snb** [friendlyanon/CFW2OFW-Helper#27]
hello, i tried to convert dark souls 2, and when it reached the npdata part i got a missing dll error. i downloaded a fix but nothing happened, and when i run make_npdata it shows the same error. also when i try to run the helper now, it doesnt recognise the PS3_GAME file. i dont really know what to do and what these all mean, i just followed a youtube tutorial.

![image](https://user-images.githubusercontent.com/50555027/57586534-d7f2b200-74ff-11e9-85cf-e2f74459a7ec.png)

**Comment by friendlyanon** [comment]
You are missing [Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784).

Any reason why you aren't just installing [PS3Xploit](https://www.reddit.com/r/ps3homebrew/wiki/ps3xploit_han) tho?

**Comment by oresths-snb** [comment]
I have PS3Xploit but I thought even with it I had to download backups to get on my ps3 with CFW2OFW

**Comment by oresths-snb** [comment]
Also, I downloaded the dll but it didnt work

**Comment by oresths-snb** [comment]
i literally redownloaded the game, the helper, and the dll yet it keeps crashing on that part

**Comment by friendlyanon** [comment]
I didn't link a single DLL to you. The entire VC++ Redistributable Package is necessary. You should really install a backup manager and use that tho.
