### ISSUE TITLE
make_npdata still giving errors in same fashion as a closed issue

### ISSUE THREAD

**Issue by jabbrowocky** [friendlyanon/CFW2OFW-Helper#29]
I'm getting an MVSCR120.dll error telling me to reinstall the program (not installed), can someone help me make meaning of this, all the research I've done so far has said to either reinstall the program which isn't an option because this isn't installed, or to reinstall my c++ redists (which I did).  I'm still recieving unending errors.

OS windows 10 x64

**Comment by Lyrx997** [comment]
try downloading the specific .dll file and paste it in System32 and SysWOW64

**Comment by friendlyanon** [comment]
This isn't an issue with make_npdata.  
You need to install the VC++ 2013 Redistributable from Microsoft.
