### ISSUE TITLE
"Corrupted Data" error on all games

### ISSUE THREAD

**Issue by Trypticon8** [friendlyanon/CFW2OFW-Helper#6]
I made a few posts about this issue over on /r/PS3Homebrew, /r/PS3Hacks and PSXHax. Got mostly no response from reddit, but did from PSXHax where I was told to come over here and post this in case I wasn't able to solve my issue.

The issue : 

After converting my games with the tool (I made sure it was the latest version), copying them over to my CFW PS3 and rebuilding the database, every single one of them said "Corrupted Data". If I click the "Check" button I get something like this (This is from BF4 in this case) :
 "STATUS : ERROR (Log was not saved)
Checking Unknown Data.(,"/dev_hdd0/game/Battlefield_4_(BLUS31162)")
Battlefield_4_(BLUS31162): Unsupported Directory Type(ffffffff)."

Games I've tried : 

1. CoD Ghosts (BLUS31270)
2. CoD BO3 (BLES02166)
3. CoD AW (BLUS31466)
4. GTA 5 (BLES01807)
5. BF4 (BLUS31162)
6. BF3 (BLES01275)
7. Midnight Club L.A (Not the complete edition, BLES00362)

Things I've tried : 

Converting and copying games over again.
Trying other games.
Switching from DEX to CEX completely (Rebug 4.81.2 REX).

I ran into a [single person](http://www.nextgenupdate.com/forums/ps3-mods-answered-questions/878384-corrupted-data-xmb.html) who had this same issue, except his issue created a log file, wouldn't let him convert from CEX to DEX, and was solved by using another CFW (Apparently he had the wrong CFW installed). Now, to my knowledge you'd only ever install D-REX Rebug versions on non-retail/dev hardware for PS3, not the normal retail versions, so I have not tried this. 

I'm really lost and would just like some clarity and hopefully a fix to my problem. 

Thanks in advance!

**Comment by friendlyanon** [comment]
This issue doesn't seem to be one related to my tool. You are welcome to join Derf's Discord for the PS3Homebrew subreddit for better assistance or refer to the guide: https://www.reddit.com/r/ps3homebrew/wiki/dtu
